# Generated by Django 3.2.5 on 2021-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Lifestyle', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Full of text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
