# Generated by Django 3.2.5 on 2021-07-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210721_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
