# Generated by Django 3.2.5 on 2021-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210721_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('HJ', 'Humphrey Haj')], max_length=2),
        ),
    ]
