# Generated by Django 3.2.5 on 2021-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='../static/images/default-image.jpg', upload_to='../static/images'),
        ),
    ]
